name: Action to Upload Artifacts from Custom Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Custom Action to create txt files
        uses: gpranaykumar/GithubCustomActions/CreateTxtFilesUploadArtifacts@main
        
      - name: END
        shell: pwsh
        run: |
          echo "END"
        
        
