name: Content to Summary Tab

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set Multi-Line Value in PowerShell Variable
        id: step1
        shell: pwsh
        run: |
          $multiLineMarkdown = @"
          # Header 1
          This is a paragraph with **bold** text and *italic* text.

          **Bold**
          
          - Item 1
          - Item 2
          - Item 3
          
          > This is a blockquote.
                    
          For more information, visit [GitHub](https://github.com).

          **Table**
          |  SNo | Task |
          | -----| -----|
          | 1    |  Hello |
          "@
          $multiLine = @"
          Hello
          pranay
          "@
          echo $multiLineMarkdown | Out-File -FilePath "${{github.workspace}}\res1.md"
          $res2 = @"
          #Pester Code Coverage Result
          | Result        | Passed      | 
          | TotalCount    | 50   |
          | PassedCount   | 50  |
          | FailedCount   | 0  |
          | SkippedCount  | 0 |
          | CodeCoverage  | 85% |
          "@
          echo $res2 | Out-File -FilePath "${{github.workspace}}\res2.md"
          Write-Host "The markdown content is:"
          Write-Host $multiLineMarkdown

          echo $res2
         
      
      - name: Set Multi-Line Value in PowerShell Variable
        id: step2
        shell: pwsh
        run: |
            Get-Content "${{github.workspace}}\res1.md" >> $env:GITHUB_STEP_SUMMARY
            Get-Content "${{github.workspace}}\res2.md" >> $env:GITHUB_STEP_SUMMARY
