name: Content to Summary Tab

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set Multi-Line Value in PowerShell Variable
        shell: pwsh
        run: |
          $multiLineMarkdown = @"
          # Header 1
          This is a paragraph with **bold** text and *italic* text.
          
          - Item 1
          - Item 2
          - Item 3
          
          > This is a blockquote.
                    
          For more information, visit [GitHub](https://github.com).
          "@
          
          Write-Host "The markdown content is:"
          Write-Host $multiLineMarkdown
          echo $multiLineMarkdown >> $env:GITHUB_STEP_SUMMARY
