name: Content to Summary Tab

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set Multi-Line Value in PowerShell Variable
        id: step1
        shell: pwsh
        run: |
          $multiLineMarkdown = @"
          # Header 1
          This is a paragraph with **bold** text and *italic* text.

          **Bold**
          
          - Item 1
          - Item 2
          - Item 3
          
          > This is a blockquote.
                    
          For more information, visit [GitHub](https://github.com).

          **Table**
          |  SNo | Task |
          | -----| -----|
          | 1    |  Hello |
          "@
          "res=$multiLineMarkdown" >> $Env:GITHUB_OUTPUT
          Write-Host "The markdown content is:"
          Write-Host $multiLineMarkdown
         
      
      - name: Set Multi-Line Value in PowerShell Variable
        id: step2
        shell: pwsh
        run: |
           echo ${{steps.step1.outputs.res}} >> $env:GITHUB_STEP_SUMMARY
